#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
	/app/calibre-web
	
# move database to /config
## copy config
[[ ! -e /config/app.db ]] && \
	cp /defaults/app.db /config/app.db && \
	ln -s /config/app.db /app/calibre-web/app.db
